# frozen_string_literal: true

module Mailchimp
  module Types
    module AudiencesContactLanguage
      extend Mailchimp::Internal::Types::Enum

      EMPTY = ""
      EN = "en"
      AR = "ar"
      AF = "af"
      BE = "be"
      BG = "bg"
      CA = "ca"
      ZH = "zh"
      ZH_CN = "zh_CN"
      HR = "hr"
      CS = "cs"
      DA = "da"
      NL = "nl"
      ET = "et"
      FA = "fa"
      FI = "fi"
      FR = "fr"
      FR_CA = "fr_CA"
      DE = "de"
      EL = "el"
      HE = "he"
      HI = "hi"
      HU = "hu"
      IS = "is"
      ID = "id"
      GA = "ga"
      IT = "it"
      JA = "ja"
      KM = "km"
      KO = "ko"
      LV = "lv"
      LT = "lt"
      MT = "mt"
      MS = "ms"
      MK = "mk"
      NO = "no"
      PL = "pl"
      PT = "pt"
      PT_PT = "pt_PT"
      RO = "ro"
      RU = "ru"
      SR = "sr"
      SK = "sk"
      SL = "sl"
      ES = "es"
      ES_ES = "es_ES"
      SW = "sw"
      SV = "sv"
      TA = "ta"
      TH = "th"
      TR = "tr"
      UK = "uk"
      VI = "vi"
    end
  end
end
